# Generated by Django 3.0.7 on 2020-11-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorylang',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('tr', 'Türkçe'), ('ru', 'Pусский'), ('hi', 'हिंदी द्वारा'), ('ar', 'ˈerəbik')], max_length=6),
        ),
        migrations.AlterField(
            model_name='productlang',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('tr', 'Türkçe'), ('ru', 'Pусский'), ('hi', 'हिंदी द्वारा'), ('ar', 'ˈerəbik')], max_length=6),
        ),
    ]
