# Generated by Django 3.0.7 on 2020-11-27 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201127_0739'),
        ('currencies', '0006_increase_name_max_length'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='currency',
            field=models.ForeignKey(blank=True, default='SAR', null=True, on_delete=django.db.models.deletion.CASCADE, to='currencies.Currency'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.ForeignKey(blank=True, default='العربية', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Language'),
        ),
    ]
